version: '3.7'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  altituderando:
    image: altituderando:latest
    depends_on:
      - mongodb
      - elasticsearch
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      STREAMLIT_HOST: streamlit
      STREAMLIT_PORT: 8501
    ports:
      - "8501:8501"

volumes:
  mongodb_data: 